/*
 *  This file was autogenerated by the GPUdb schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */
package com.gisfederal.gpudb.protocol;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.apache.avro.Schema;
import org.apache.avro.SchemaBuilder;
import org.apache.avro.generic.GenericData;
import org.apache.avro.generic.IndexedRecord;


/**
 * A set of results returned by {@link
 * com.gisfederal.gpudb.GPUdb#alterTableProperties(AlterTablePropertiesRequest)}.
 */
public class AlterTablePropertiesResponse implements IndexedRecord {
    private static final Schema schema$ = SchemaBuilder
            .record("AlterTablePropertiesResponse")
            .namespace("com.gisfederal.gpudb")
            .fields()
                .name("tableNames").type().array().items().stringType().noDefault()
                .name("propertiesMap").type().map().values().stringType().noDefault()
            .endRecord();


    /**
     * This method supports the Avro framework and is not intended to be called
     * directly by the user.
     * 
     * @return  the schema for the class.
     * 
     */
    public static Schema getClassSchema() {
        return schema$;
    }

    private List<String> tableNames;
    private Map<String, String> propertiesMap;


    /**
     * Constructs an AlterTablePropertiesResponse object with default
     * parameters.
     */
    public AlterTablePropertiesResponse() {
    }

    /**
     * 
     * @return names of the tables whose properties have been updated.
     * 
     */
    public List<String> getTableNames() {
        return tableNames;
    }

    /**
     * 
     * @param tableNames  names of the tables whose properties have been
     *                    updated.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public AlterTablePropertiesResponse setTableNames(List<String> tableNames) {
        this.tableNames = (tableNames == null) ? new ArrayList<String>() : tableNames;
        return this;
    }

    /**
     * 
     * @return Value of {@code propertiesMap}.
     * 
     */
    public Map<String, String> getPropertiesMap() {
        return propertiesMap;
    }

    /**
     * 
     * @param propertiesMap  Value of {@code propertiesMap}.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public AlterTablePropertiesResponse setPropertiesMap(Map<String, String> propertiesMap) {
        this.propertiesMap = (propertiesMap == null) ? new LinkedHashMap<String, String>() : propertiesMap;
        return this;
    }

    /**
     * This method supports the Avro framework and is not intended to be called
     * directly by the user.
     * 
     * @return the schema object describing this class.
     * 
     */
    @Override
    public Schema getSchema() {
        return schema$;
    }

    /**
     * This method supports the Avro framework and is not intended to be called
     * directly by the user.
     * 
     * @param index  the position of the field to get
     * 
     * @return value of the field with the given index.
     * 
     * @throws IndexOutOfBoundsException
     * 
     */
    @Override
    public Object get(int index) {
        switch (index) {
            case 0:
                return this.tableNames;

            case 1:
                return this.propertiesMap;

            default:
                throw new IndexOutOfBoundsException("Invalid index specified.");
        }
    }

    /**
     * This method supports the Avro framework and is not intended to be called
     * directly by the user.
     * 
     * @param index  the position of the field to set
     * @param value  the value to set
     * 
     * @throws IndexOutOfBoundsException
     * 
     */
    @Override
    @SuppressWarnings("unchecked")
    public void put(int index, Object value) {
        switch (index) {
            case 0:
                this.tableNames = (List<String>)value;
                break;

            case 1:
                this.propertiesMap = (Map<String, String>)value;
                break;

            default:
                throw new IndexOutOfBoundsException("Invalid index specified.");
        }
    }

    @Override
    public boolean equals(Object obj) {
        if( obj == this ) {
            return true;
        }

        if( (obj == null) || (obj.getClass() != this.getClass()) ) {
            return false;
        }

        AlterTablePropertiesResponse that = (AlterTablePropertiesResponse)obj;

        return ( this.tableNames.equals( that.tableNames )
                 && this.propertiesMap.equals( that.propertiesMap ) );
    }

    @Override
    public String toString() {
        GenericData gd = GenericData.get();
        StringBuilder builder = new StringBuilder();
        builder.append( gd.toString( "tableNames" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.tableNames ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "propertiesMap" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.propertiesMap ) );

        return builder.toString();
    }

    @Override
    public int hashCode() {
        int hashCode = 1;
        hashCode = (31 * hashCode) + this.tableNames.hashCode();
        hashCode = (31 * hashCode) + this.propertiesMap.hashCode();
        return hashCode;
    }

}
