/*
 *  This file was autogenerated by the GPUdb schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */
package com.gisfederal.gpudb.protocol;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.apache.avro.Schema;
import org.apache.avro.SchemaBuilder;
import org.apache.avro.generic.GenericData;
import org.apache.avro.generic.IndexedRecord;


/**
 * A set of parameters for {@link
 * com.gisfederal.gpudb.GPUdb#visualizeImageHeatmapClassbreak(VisualizeImageHeatmapClassbreakRequest)}.
 * <p>
 * Generates 'class break' rasterized heatmap image tiles for an area of
 * interest using the given tables and the provided parameters.
 * <p>
 * A class break rendering is where data from one or more GPUdb tables is
 * rasterized with styling applied on a per-class basis. GPUdb supports class
 * breaks based on one or more data columns. Distinct values (for strings) or
 * ranges (for numeric attributes) must be provided in the
 * cb_column_name1/cb_vals1 and cb_column_name2/cb_vals2 parameters. The
 * styling parameters must be specified for each class.
 * <p>
 * All color values must be in the format RRGGBB or AARRGGBB (to specify the
 * alpha value).
 */
public class VisualizeImageHeatmapClassbreakRequest implements IndexedRecord {
    private static final Schema schema$ = SchemaBuilder
            .record("VisualizeImageHeatmapClassbreakRequest")
            .namespace("com.gisfederal.gpudb")
            .fields()
                .name("tableNames").type().array().items().stringType().noDefault()
                .name("xColumnName").type().stringType().noDefault()
                .name("yColumnName").type().stringType().noDefault()
                .name("cbColumnName").type().stringType().noDefault()
                .name("cbVals").type().array().items().stringType().noDefault()
                .name("cbRanges").type().array().items().stringType().noDefault()
                .name("minX").type().doubleType().noDefault()
                .name("maxX").type().doubleType().noDefault()
                .name("minY").type().doubleType().noDefault()
                .name("maxY").type().doubleType().noDefault()
                .name("width").type().intType().noDefault()
                .name("height").type().intType().noDefault()
                .name("projection").type().stringType().noDefault()
                .name("colormaps").type().array().items().stringType().noDefault()
                .name("blurRadii").type().array().items().intType().noDefault()
                .name("bgColor").type().longType().noDefault()
                .name("gradientStartColors").type().array().items().longType().noDefault()
                .name("gradientEndColors").type().array().items().longType().noDefault()
                .name("options").type().map().values().stringType().noDefault()
            .endRecord();


    /**
     * This method supports the Avro framework and is not intended to be called
     * directly by the user.
     * 
     * @return  the schema for the class.
     * 
     */
    public static Schema getClassSchema() {
        return schema$;
    }


    /**
     * Spatial Reference System (i.e. EPSG Code).
     * A set of string constants for the parameter {@code projection}.
     */
    public static final class Projection {
        public static final String EPSG_4326 = "EPSG:4326";
        public static final String PLATE_CARREE = "PLATE_CARREE";
        public static final String _900913 = "900913";
        public static final String EPSG_900913 = "EPSG:900913";
        public static final String _102100 = "102100";
        public static final String EPSG_102100 = "EPSG:102100";
        public static final String _3857 = "3857";
        public static final String EPSG_3857 = "EPSG:3857";
        public static final String WEB_MERCATOR = "WEB_MERCATOR";

        private Projection() {  }
    }

    private List<String> tableNames;
    private String xColumnName;
    private String yColumnName;
    private String cbColumnName;
    private List<String> cbVals;
    private List<String> cbRanges;
    private double minX;
    private double maxX;
    private double minY;
    private double maxY;
    private int width;
    private int height;
    private String projection;
    private List<String> colormaps;
    private List<Integer> blurRadii;
    private long bgColor;
    private List<Long> gradientStartColors;
    private List<Long> gradientEndColors;
    private Map<String, String> options;


    /**
     * Constructs a VisualizeImageHeatmapClassbreakRequest object with default
     * parameters.
     */
    public VisualizeImageHeatmapClassbreakRequest() {
        tableNames = new ArrayList<>();
        xColumnName = "";
        yColumnName = "";
        cbColumnName = "";
        cbVals = new ArrayList<>();
        cbRanges = new ArrayList<>();
        projection = "";
        colormaps = new ArrayList<>();
        blurRadii = new ArrayList<>();
        gradientStartColors = new ArrayList<>();
        gradientEndColors = new ArrayList<>();
        options = new LinkedHashMap<>();
    }

    /**
     * Constructs a VisualizeImageHeatmapClassbreakRequest object with the
     * specified parameters.
     * 
     * @param tableNames  Name of the table containing the data for the various
     *                    layers to be rendered.
     * @param xColumnName  Name of the column containing the x coordinates.
     * @param yColumnName  Name of the column containing the y coordinates.
     * @param cbColumnName  Name of the column for the class break.
     * @param cbVals  Comma separated list of values (e.g. '0,5,10,15,30').
     * @param cbRanges  Comma separated list of ranges (e.g. '0:5,5:10,15:30').
     * @param minX  Lower bound for the x values.
     * @param maxX  Upper bound for the x values.
     * @param minY  Lower bound for the y values.
     * @param maxY  Upper bound for the y values.
     * @param width  Width of the generated image.
     * @param height  Height of the generated image.
     * @param projection  Spatial Reference System (i.e. EPSG Code).
     * @param colormaps  Colormap for the heat map.
     * @param blurRadii  Blurring radius for the heat map.  The minimum allowed
     *                   value is 1. The maximum allowed value is 32.
     * @param bgColor  Background color of the generated image.
     * @param gradientStartColors  User defined gradient start color for the
     *                             heat map.
     * @param gradientEndColors  User defined gradient end color for the heat
     *                           map.
     * @param options  Optional parameters.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest(List<String> tableNames, String xColumnName, String yColumnName, String cbColumnName, List<String> cbVals, List<String> cbRanges, double minX, double maxX, double minY, double maxY, int width, int height, String projection, List<String> colormaps, List<Integer> blurRadii, long bgColor, List<Long> gradientStartColors, List<Long> gradientEndColors, Map<String, String> options) {
        this.tableNames = (tableNames == null) ? new ArrayList<String>() : tableNames;
        this.xColumnName = (xColumnName == null) ? "" : xColumnName;
        this.yColumnName = (yColumnName == null) ? "" : yColumnName;
        this.cbColumnName = (cbColumnName == null) ? "" : cbColumnName;
        this.cbVals = (cbVals == null) ? new ArrayList<String>() : cbVals;
        this.cbRanges = (cbRanges == null) ? new ArrayList<String>() : cbRanges;
        this.minX = minX;
        this.maxX = maxX;
        this.minY = minY;
        this.maxY = maxY;
        this.width = width;
        this.height = height;
        this.projection = (projection == null) ? "" : projection;
        this.colormaps = (colormaps == null) ? new ArrayList<String>() : colormaps;
        this.blurRadii = (blurRadii == null) ? new ArrayList<Integer>() : blurRadii;
        this.bgColor = bgColor;
        this.gradientStartColors = (gradientStartColors == null) ? new ArrayList<Long>() : gradientStartColors;
        this.gradientEndColors = (gradientEndColors == null) ? new ArrayList<Long>() : gradientEndColors;
        this.options = (options == null) ? new LinkedHashMap<String, String>() : options;
    }

    /**
     * 
     * @return Name of the table containing the data for the various layers to
     *         be rendered.
     * 
     */
    public List<String> getTableNames() {
        return tableNames;
    }

    /**
     * 
     * @param tableNames  Name of the table containing the data for the various
     *                    layers to be rendered.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setTableNames(List<String> tableNames) {
        this.tableNames = (tableNames == null) ? new ArrayList<String>() : tableNames;
        return this;
    }

    /**
     * 
     * @return Name of the column containing the x coordinates.
     * 
     */
    public String getXColumnName() {
        return xColumnName;
    }

    /**
     * 
     * @param xColumnName  Name of the column containing the x coordinates.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setXColumnName(String xColumnName) {
        this.xColumnName = (xColumnName == null) ? "" : xColumnName;
        return this;
    }

    /**
     * 
     * @return Name of the column containing the y coordinates.
     * 
     */
    public String getYColumnName() {
        return yColumnName;
    }

    /**
     * 
     * @param yColumnName  Name of the column containing the y coordinates.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setYColumnName(String yColumnName) {
        this.yColumnName = (yColumnName == null) ? "" : yColumnName;
        return this;
    }

    /**
     * 
     * @return Name of the column for the class break.
     * 
     */
    public String getCbColumnName() {
        return cbColumnName;
    }

    /**
     * 
     * @param cbColumnName  Name of the column for the class break.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setCbColumnName(String cbColumnName) {
        this.cbColumnName = (cbColumnName == null) ? "" : cbColumnName;
        return this;
    }

    /**
     * 
     * @return Comma separated list of values (e.g. '0,5,10,15,30').
     * 
     */
    public List<String> getCbVals() {
        return cbVals;
    }

    /**
     * 
     * @param cbVals  Comma separated list of values (e.g. '0,5,10,15,30').
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setCbVals(List<String> cbVals) {
        this.cbVals = (cbVals == null) ? new ArrayList<String>() : cbVals;
        return this;
    }

    /**
     * 
     * @return Comma separated list of ranges (e.g. '0:5,5:10,15:30').
     * 
     */
    public List<String> getCbRanges() {
        return cbRanges;
    }

    /**
     * 
     * @param cbRanges  Comma separated list of ranges (e.g. '0:5,5:10,15:30').
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setCbRanges(List<String> cbRanges) {
        this.cbRanges = (cbRanges == null) ? new ArrayList<String>() : cbRanges;
        return this;
    }

    /**
     * 
     * @return Lower bound for the x values.
     * 
     */
    public double getMinX() {
        return minX;
    }

    /**
     * 
     * @param minX  Lower bound for the x values.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setMinX(double minX) {
        this.minX = minX;
        return this;
    }

    /**
     * 
     * @return Upper bound for the x values.
     * 
     */
    public double getMaxX() {
        return maxX;
    }

    /**
     * 
     * @param maxX  Upper bound for the x values.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setMaxX(double maxX) {
        this.maxX = maxX;
        return this;
    }

    /**
     * 
     * @return Lower bound for the y values.
     * 
     */
    public double getMinY() {
        return minY;
    }

    /**
     * 
     * @param minY  Lower bound for the y values.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setMinY(double minY) {
        this.minY = minY;
        return this;
    }

    /**
     * 
     * @return Upper bound for the y values.
     * 
     */
    public double getMaxY() {
        return maxY;
    }

    /**
     * 
     * @param maxY  Upper bound for the y values.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setMaxY(double maxY) {
        this.maxY = maxY;
        return this;
    }

    /**
     * 
     * @return Width of the generated image.
     * 
     */
    public int getWidth() {
        return width;
    }

    /**
     * 
     * @param width  Width of the generated image.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setWidth(int width) {
        this.width = width;
        return this;
    }

    /**
     * 
     * @return Height of the generated image.
     * 
     */
    public int getHeight() {
        return height;
    }

    /**
     * 
     * @param height  Height of the generated image.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setHeight(int height) {
        this.height = height;
        return this;
    }

    /**
     * 
     * @return Spatial Reference System (i.e. EPSG Code).
     * 
     */
    public String getProjection() {
        return projection;
    }

    /**
     * 
     * @param projection  Spatial Reference System (i.e. EPSG Code).
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setProjection(String projection) {
        this.projection = (projection == null) ? "" : projection;
        return this;
    }

    /**
     * 
     * @return Colormap for the heat map.
     * 
     */
    public List<String> getColormaps() {
        return colormaps;
    }

    /**
     * 
     * @param colormaps  Colormap for the heat map.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setColormaps(List<String> colormaps) {
        this.colormaps = (colormaps == null) ? new ArrayList<String>() : colormaps;
        return this;
    }

    /**
     * 
     * @return Blurring radius for the heat map.  The minimum allowed value is
     *         1. The maximum allowed value is 32.
     * 
     */
    public List<Integer> getBlurRadii() {
        return blurRadii;
    }

    /**
     * 
     * @param blurRadii  Blurring radius for the heat map.  The minimum allowed
     *                   value is 1. The maximum allowed value is 32.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setBlurRadii(List<Integer> blurRadii) {
        this.blurRadii = (blurRadii == null) ? new ArrayList<Integer>() : blurRadii;
        return this;
    }

    /**
     * 
     * @return Background color of the generated image.
     * 
     */
    public long getBgColor() {
        return bgColor;
    }

    /**
     * 
     * @param bgColor  Background color of the generated image.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setBgColor(long bgColor) {
        this.bgColor = bgColor;
        return this;
    }

    /**
     * 
     * @return User defined gradient start color for the heat map.
     * 
     */
    public List<Long> getGradientStartColors() {
        return gradientStartColors;
    }

    /**
     * 
     * @param gradientStartColors  User defined gradient start color for the
     *                             heat map.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setGradientStartColors(List<Long> gradientStartColors) {
        this.gradientStartColors = (gradientStartColors == null) ? new ArrayList<Long>() : gradientStartColors;
        return this;
    }

    /**
     * 
     * @return User defined gradient end color for the heat map.
     * 
     */
    public List<Long> getGradientEndColors() {
        return gradientEndColors;
    }

    /**
     * 
     * @param gradientEndColors  User defined gradient end color for the heat
     *                           map.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setGradientEndColors(List<Long> gradientEndColors) {
        this.gradientEndColors = (gradientEndColors == null) ? new ArrayList<Long>() : gradientEndColors;
        return this;
    }

    /**
     * 
     * @return Optional parameters.
     * 
     */
    public Map<String, String> getOptions() {
        return options;
    }

    /**
     * 
     * @param options  Optional parameters.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public VisualizeImageHeatmapClassbreakRequest setOptions(Map<String, String> options) {
        this.options = (options == null) ? new LinkedHashMap<String, String>() : options;
        return this;
    }

    /**
     * This method supports the Avro framework and is not intended to be called
     * directly by the user.
     * 
     * @return the schema object describing this class.
     * 
     */
    @Override
    public Schema getSchema() {
        return schema$;
    }

    /**
     * This method supports the Avro framework and is not intended to be called
     * directly by the user.
     * 
     * @param index  the position of the field to get
     * 
     * @return value of the field with the given index.
     * 
     * @throws IndexOutOfBoundsException
     * 
     */
    @Override
    public Object get(int index) {
        switch (index) {
            case 0:
                return this.tableNames;

            case 1:
                return this.xColumnName;

            case 2:
                return this.yColumnName;

            case 3:
                return this.cbColumnName;

            case 4:
                return this.cbVals;

            case 5:
                return this.cbRanges;

            case 6:
                return this.minX;

            case 7:
                return this.maxX;

            case 8:
                return this.minY;

            case 9:
                return this.maxY;

            case 10:
                return this.width;

            case 11:
                return this.height;

            case 12:
                return this.projection;

            case 13:
                return this.colormaps;

            case 14:
                return this.blurRadii;

            case 15:
                return this.bgColor;

            case 16:
                return this.gradientStartColors;

            case 17:
                return this.gradientEndColors;

            case 18:
                return this.options;

            default:
                throw new IndexOutOfBoundsException("Invalid index specified.");
        }
    }

    /**
     * This method supports the Avro framework and is not intended to be called
     * directly by the user.
     * 
     * @param index  the position of the field to set
     * @param value  the value to set
     * 
     * @throws IndexOutOfBoundsException
     * 
     */
    @Override
    @SuppressWarnings("unchecked")
    public void put(int index, Object value) {
        switch (index) {
            case 0:
                this.tableNames = (List<String>)value;
                break;

            case 1:
                this.xColumnName = (String)value;
                break;

            case 2:
                this.yColumnName = (String)value;
                break;

            case 3:
                this.cbColumnName = (String)value;
                break;

            case 4:
                this.cbVals = (List<String>)value;
                break;

            case 5:
                this.cbRanges = (List<String>)value;
                break;

            case 6:
                this.minX = (Double)value;
                break;

            case 7:
                this.maxX = (Double)value;
                break;

            case 8:
                this.minY = (Double)value;
                break;

            case 9:
                this.maxY = (Double)value;
                break;

            case 10:
                this.width = (Integer)value;
                break;

            case 11:
                this.height = (Integer)value;
                break;

            case 12:
                this.projection = (String)value;
                break;

            case 13:
                this.colormaps = (List<String>)value;
                break;

            case 14:
                this.blurRadii = (List<Integer>)value;
                break;

            case 15:
                this.bgColor = (Long)value;
                break;

            case 16:
                this.gradientStartColors = (List<Long>)value;
                break;

            case 17:
                this.gradientEndColors = (List<Long>)value;
                break;

            case 18:
                this.options = (Map<String, String>)value;
                break;

            default:
                throw new IndexOutOfBoundsException("Invalid index specified.");
        }
    }

    @Override
    public boolean equals(Object obj) {
        if( obj == this ) {
            return true;
        }

        if( (obj == null) || (obj.getClass() != this.getClass()) ) {
            return false;
        }

        VisualizeImageHeatmapClassbreakRequest that = (VisualizeImageHeatmapClassbreakRequest)obj;

        return ( this.tableNames.equals( that.tableNames )
                 && this.xColumnName.equals( that.xColumnName )
                 && this.yColumnName.equals( that.yColumnName )
                 && this.cbColumnName.equals( that.cbColumnName )
                 && this.cbVals.equals( that.cbVals )
                 && this.cbRanges.equals( that.cbRanges )
                 && ( (Double)this.minX ).equals( (Double)that.minX )
                 && ( (Double)this.maxX ).equals( (Double)that.maxX )
                 && ( (Double)this.minY ).equals( (Double)that.minY )
                 && ( (Double)this.maxY ).equals( (Double)that.maxY )
                 && ( this.width == that.width )
                 && ( this.height == that.height )
                 && this.projection.equals( that.projection )
                 && this.colormaps.equals( that.colormaps )
                 && this.blurRadii.equals( that.blurRadii )
                 && ( this.bgColor == that.bgColor )
                 && this.gradientStartColors.equals( that.gradientStartColors )
                 && this.gradientEndColors.equals( that.gradientEndColors )
                 && this.options.equals( that.options ) );
    }

    @Override
    public String toString() {
        GenericData gd = GenericData.get();
        StringBuilder builder = new StringBuilder();
        builder.append( gd.toString( "tableNames" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.tableNames ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "xColumnName" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.xColumnName ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "yColumnName" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.yColumnName ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "cbColumnName" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.cbColumnName ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "cbVals" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.cbVals ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "cbRanges" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.cbRanges ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "minX" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.minX ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "maxX" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.maxX ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "minY" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.minY ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "maxY" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.maxY ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "width" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.width ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "height" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.height ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "projection" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.projection ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "colormaps" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.colormaps ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "blurRadii" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.blurRadii ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "bgColor" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.bgColor ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "gradientStartColors" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.gradientStartColors ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "gradientEndColors" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.gradientEndColors ) );
        builder.append( gd.toString( "," ) );
        builder.append( gd.toString( "options" ) );
        builder.append( gd.toString( ":" ) );
        builder.append( gd.toString( this.options ) );

        return builder.toString();
    }

    @Override
    public int hashCode() {
        int hashCode = 1;
        hashCode = (31 * hashCode) + this.tableNames.hashCode();
        hashCode = (31 * hashCode) + this.xColumnName.hashCode();
        hashCode = (31 * hashCode) + this.yColumnName.hashCode();
        hashCode = (31 * hashCode) + this.cbColumnName.hashCode();
        hashCode = (31 * hashCode) + this.cbVals.hashCode();
        hashCode = (31 * hashCode) + this.cbRanges.hashCode();
        hashCode = (31 * hashCode) + ((Double)this.minX).hashCode();
        hashCode = (31 * hashCode) + ((Double)this.maxX).hashCode();
        hashCode = (31 * hashCode) + ((Double)this.minY).hashCode();
        hashCode = (31 * hashCode) + ((Double)this.maxY).hashCode();
        hashCode = (31 * hashCode) + this.width;
        hashCode = (31 * hashCode) + this.height;
        hashCode = (31 * hashCode) + this.projection.hashCode();
        hashCode = (31 * hashCode) + this.colormaps.hashCode();
        hashCode = (31 * hashCode) + this.blurRadii.hashCode();
        hashCode = (31 * hashCode) + ((Long)this.bgColor).hashCode();
        hashCode = (31 * hashCode) + this.gradientStartColors.hashCode();
        hashCode = (31 * hashCode) + this.gradientEndColors.hashCode();
        hashCode = (31 * hashCode) + this.options.hashCode();
        return hashCode;
    }

}
