/*
 *  This file was autogenerated by the GPUdb schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */
package com.gpudb.protocol;

import java.util.LinkedHashMap;
import java.util.Map;
import org.apache.avro.Schema;
import org.apache.avro.SchemaBuilder;
import org.apache.avro.generic.GenericData;
import org.apache.avro.generic.IndexedRecord;


/**
 * A set of parameters for {@link
 * com.gpudb.GPUdb#alterDatasink(AlterDatasinkRequest)}.
 * <p>
 * Alters the properties of an existing <a
 * href="../../../../../../concepts/data_sinks/" target="_top">data sink</a>
 */
public class AlterDatasinkRequest implements IndexedRecord {
    private static final Schema schema$ = SchemaBuilder
            .record("AlterDatasinkRequest")
            .namespace("com.gpudb")
            .fields()
                .name("name").type().stringType().noDefault()
                .name("datasinkUpdatesMap").type().map().values().stringType().noDefault()
                .name("options").type().map().values().stringType().noDefault()
            .endRecord();


    /**
     * This method supports the Avro framework and is not intended to be called
     * directly by the user.
     * 
     * @return  the schema for the class.
     * 
     */
    public static Schema getClassSchema() {
        return schema$;
    }


    /**
     * Map containing the properties of the data sink to be updated. Error if
     * empty.
     * <ul>
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#DESTINATION
     * DESTINATION}: Destination for the output data in format
     * 'destination_type://path[:port]'.
     * <p>
     * Supported destination types are 'http', 'https' and 'kafka'.
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#CONNECTION_TIMEOUT
     * CONNECTION_TIMEOUT}: Timeout in seconds for connecting to this sink
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#WAIT_TIMEOUT
     * WAIT_TIMEOUT}: Timeout in seconds for waiting for a response from this
     * sink
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#CREDENTIAL
     * CREDENTIAL}: Name of the <a
     * href="../../../../../../concepts/credentials/"
     * target="_top">credential</a> object to be used in this data sink
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#KAFKA_TOPIC_NAME
     * KAFKA_TOPIC_NAME}: Name of the Kafka topic to use for this data sink, if
     * it references a Kafka broker
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#MAX_BATCH_SIZE
     * MAX_BATCH_SIZE}: Maximum number of records per notification message.
     * The default value is '1'.
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#MAX_MESSAGE_SIZE
     * MAX_MESSAGE_SIZE}: Maximum size in bytes of each notification message.
     * The default value is '1000000'.
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#JSON_FORMAT
     * JSON_FORMAT}: The desired format of JSON encoded notifications message.
     * <p>
     * If {@code nested}, records are returned as an array.
     * Otherwise, only a single record per messages is returned.
     * Supported values:
     * <ul>
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FLAT FLAT}
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#NESTED
     * NESTED}
     * </ul>
     * The default value is {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FLAT FLAT}.
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#SKIP_VALIDATION
     * SKIP_VALIDATION}: Bypass validation of connection to this data sink.
     * Supported values:
     * <ul>
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#TRUE TRUE}
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FALSE FALSE}
     * </ul>
     * The default value is {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FALSE FALSE}.
     *         <li> {@link
     * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#SCHEMA_NAME
     * SCHEMA_NAME}: Updates the schema name.  If {@code schema_name}
     * doesn't exist, an error will be thrown. If {@code schema_name} is empty,
     * then the user's
     * default schema will be used.
     * </ul>
     * A set of string constants for the parameter {@code datasinkUpdatesMap}.
     */
    public static final class DatasinkUpdatesMap {

        /**
         * Destination for the output data in format
         * 'destination_type://path[:port]'.
         * <p>
         * Supported destination types are 'http', 'https' and 'kafka'.
         */
        public static final String DESTINATION = "destination";

        /**
         * Timeout in seconds for connecting to this sink
         */
        public static final String CONNECTION_TIMEOUT = "connection_timeout";

        /**
         * Timeout in seconds for waiting for a response from this sink
         */
        public static final String WAIT_TIMEOUT = "wait_timeout";

        /**
         * Name of the <a href="../../../../../../concepts/credentials/"
         * target="_top">credential</a> object to be used in this data sink
         */
        public static final String CREDENTIAL = "credential";

        /**
         * Name of the Kafka topic to use for this data sink, if it references
         * a Kafka broker
         */
        public static final String KAFKA_TOPIC_NAME = "kafka_topic_name";

        /**
         * Maximum number of records per notification message.  The default
         * value is '1'.
         */
        public static final String MAX_BATCH_SIZE = "max_batch_size";

        /**
         * Maximum size in bytes of each notification message.  The default
         * value is '1000000'.
         */
        public static final String MAX_MESSAGE_SIZE = "max_message_size";

        /**
         * The desired format of JSON encoded notifications message.
         * <p>
         * If {@code nested}, records are returned as an array.
         * Otherwise, only a single record per messages is returned.
         * Supported values:
         * <ul>
         *         <li> {@link
         * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FLAT
         * FLAT}
         *         <li> {@link
         * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#NESTED
         * NESTED}
         * </ul>
         * The default value is {@link
         * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FLAT
         * FLAT}.
         */
        public static final String JSON_FORMAT = "json_format";
        public static final String FLAT = "flat";
        public static final String NESTED = "nested";

        /**
         * Bypass validation of connection to this data sink.
         * Supported values:
         * <ul>
         *         <li> {@link
         * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#TRUE
         * TRUE}
         *         <li> {@link
         * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FALSE
         * FALSE}
         * </ul>
         * The default value is {@link
         * com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FALSE
         * FALSE}.
         */
        public static final String SKIP_VALIDATION = "skip_validation";
        public static final String TRUE = "true";
        public static final String FALSE = "false";

        /**
         * Updates the schema name.  If {@code schema_name}
         * doesn't exist, an error will be thrown. If {@code schema_name} is
         * empty, then the user's
         * default schema will be used.
         */
        public static final String SCHEMA_NAME = "schema_name";

        private DatasinkUpdatesMap() {  }
    }

    private String name;
    private Map<String, String> datasinkUpdatesMap;
    private Map<String, String> options;


    /**
     * Constructs an AlterDatasinkRequest object with default parameters.
     */
    public AlterDatasinkRequest() {
        name = "";
        datasinkUpdatesMap = new LinkedHashMap<>();
        options = new LinkedHashMap<>();
    }

    /**
     * Constructs an AlterDatasinkRequest object with the specified parameters.
     * 
     * @param name  Name of the data sink to be altered. Must be an existing
     *              data sink.
     * @param datasinkUpdatesMap  Map containing the properties of the data
     *                            sink to be updated. Error if empty.
     *                            <ul>
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#DESTINATION
     *                            DESTINATION}: Destination for the output data
     *                            in format 'destination_type://path[:port]'.
     *                            Supported destination types are 'http',
     *                            'https' and 'kafka'.
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#CONNECTION_TIMEOUT
     *                            CONNECTION_TIMEOUT}: Timeout in seconds for
     *                            connecting to this sink
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#WAIT_TIMEOUT
     *                            WAIT_TIMEOUT}: Timeout in seconds for waiting
     *                            for a response from this sink
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#CREDENTIAL
     *                            CREDENTIAL}: Name of the <a
     *                            href="../../../../../../concepts/credentials/"
     *                            target="_top">credential</a> object to be
     *                            used in this data sink
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#KAFKA_TOPIC_NAME
     *                            KAFKA_TOPIC_NAME}: Name of the Kafka topic to
     *                            use for this data sink, if it references a
     *                            Kafka broker
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#MAX_BATCH_SIZE
     *                            MAX_BATCH_SIZE}: Maximum number of records
     *                            per notification message.  The default value
     *                            is '1'.
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#MAX_MESSAGE_SIZE
     *                            MAX_MESSAGE_SIZE}: Maximum size in bytes of
     *                            each notification message.  The default value
     *                            is '1000000'.
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#JSON_FORMAT
     *                            JSON_FORMAT}: The desired format of JSON
     *                            encoded notifications message.
     *                            If {@code nested}, records are returned as an
     *                            array.
     *                            Otherwise, only a single record per messages
     *                            is returned.
     *                            Supported values:
     *                            <ul>
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FLAT
     *                            FLAT}
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#NESTED
     *                            NESTED}
     *                            </ul>
     *                            The default value is {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FLAT
     *                            FLAT}.
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#SKIP_VALIDATION
     *                            SKIP_VALIDATION}: Bypass validation of
     *                            connection to this data sink.
     *                            Supported values:
     *                            <ul>
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#TRUE
     *                            TRUE}
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FALSE
     *                            FALSE}
     *                            </ul>
     *                            The default value is {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FALSE
     *                            FALSE}.
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#SCHEMA_NAME
     *                            SCHEMA_NAME}: Updates the schema name.  If
     *                            {@code schema_name}
     *                            doesn't exist, an error will be thrown. If
     *                            {@code schema_name} is empty, then the user's
     *                            default schema will be used.
     *                            </ul>
     * @param options  Optional parameters.
     * 
     */
    public AlterDatasinkRequest(String name, Map<String, String> datasinkUpdatesMap, Map<String, String> options) {
        this.name = (name == null) ? "" : name;
        this.datasinkUpdatesMap = (datasinkUpdatesMap == null) ? new LinkedHashMap<String, String>() : datasinkUpdatesMap;
        this.options = (options == null) ? new LinkedHashMap<String, String>() : options;
    }

    /**
     * 
     * @return Name of the data sink to be altered. Must be an existing data
     *         sink.
     * 
     */
    public String getName() {
        return name;
    }

    /**
     * 
     * @param name  Name of the data sink to be altered. Must be an existing
     *              data sink.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public AlterDatasinkRequest setName(String name) {
        this.name = (name == null) ? "" : name;
        return this;
    }

    /**
     * 
     * @return Map containing the properties of the data sink to be updated.
     *         Error if empty.
     *         <ul>
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#DESTINATION
     *         DESTINATION}: Destination for the output data in format
     *         'destination_type://path[:port]'.
     *         Supported destination types are 'http', 'https' and 'kafka'.
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#CONNECTION_TIMEOUT
     *         CONNECTION_TIMEOUT}: Timeout in seconds for connecting to this
     *         sink
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#WAIT_TIMEOUT
     *         WAIT_TIMEOUT}: Timeout in seconds for waiting for a response
     *         from this sink
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#CREDENTIAL
     *         CREDENTIAL}: Name of the <a
     *         href="../../../../../../concepts/credentials/"
     *         target="_top">credential</a> object to be used in this data sink
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#KAFKA_TOPIC_NAME
     *         KAFKA_TOPIC_NAME}: Name of the Kafka topic to use for this data
     *         sink, if it references a Kafka broker
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#MAX_BATCH_SIZE
     *         MAX_BATCH_SIZE}: Maximum number of records per notification
     *         message.  The default value is '1'.
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#MAX_MESSAGE_SIZE
     *         MAX_MESSAGE_SIZE}: Maximum size in bytes of each notification
     *         message.  The default value is '1000000'.
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#JSON_FORMAT
     *         JSON_FORMAT}: The desired format of JSON encoded notifications
     *         message.
     *         If {@code nested}, records are returned as an array.
     *         Otherwise, only a single record per messages is returned.
     *         Supported values:
     *         <ul>
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FLAT
     *         FLAT}
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#NESTED
     *         NESTED}
     *         </ul>
     *         The default value is {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FLAT
     *         FLAT}.
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#SKIP_VALIDATION
     *         SKIP_VALIDATION}: Bypass validation of connection to this data
     *         sink.
     *         Supported values:
     *         <ul>
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#TRUE
     *         TRUE}
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FALSE
     *         FALSE}
     *         </ul>
     *         The default value is {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FALSE
     *         FALSE}.
     *                 <li> {@link
     *         com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#SCHEMA_NAME
     *         SCHEMA_NAME}: Updates the schema name.  If {@code schema_name}
     *         doesn't exist, an error will be thrown. If {@code schema_name}
     *         is empty, then the user's
     *         default schema will be used.
     *         </ul>
     * 
     */
    public Map<String, String> getDatasinkUpdatesMap() {
        return datasinkUpdatesMap;
    }

    /**
     * 
     * @param datasinkUpdatesMap  Map containing the properties of the data
     *                            sink to be updated. Error if empty.
     *                            <ul>
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#DESTINATION
     *                            DESTINATION}: Destination for the output data
     *                            in format 'destination_type://path[:port]'.
     *                            Supported destination types are 'http',
     *                            'https' and 'kafka'.
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#CONNECTION_TIMEOUT
     *                            CONNECTION_TIMEOUT}: Timeout in seconds for
     *                            connecting to this sink
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#WAIT_TIMEOUT
     *                            WAIT_TIMEOUT}: Timeout in seconds for waiting
     *                            for a response from this sink
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#CREDENTIAL
     *                            CREDENTIAL}: Name of the <a
     *                            href="../../../../../../concepts/credentials/"
     *                            target="_top">credential</a> object to be
     *                            used in this data sink
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#KAFKA_TOPIC_NAME
     *                            KAFKA_TOPIC_NAME}: Name of the Kafka topic to
     *                            use for this data sink, if it references a
     *                            Kafka broker
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#MAX_BATCH_SIZE
     *                            MAX_BATCH_SIZE}: Maximum number of records
     *                            per notification message.  The default value
     *                            is '1'.
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#MAX_MESSAGE_SIZE
     *                            MAX_MESSAGE_SIZE}: Maximum size in bytes of
     *                            each notification message.  The default value
     *                            is '1000000'.
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#JSON_FORMAT
     *                            JSON_FORMAT}: The desired format of JSON
     *                            encoded notifications message.
     *                            If {@code nested}, records are returned as an
     *                            array.
     *                            Otherwise, only a single record per messages
     *                            is returned.
     *                            Supported values:
     *                            <ul>
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FLAT
     *                            FLAT}
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#NESTED
     *                            NESTED}
     *                            </ul>
     *                            The default value is {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FLAT
     *                            FLAT}.
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#SKIP_VALIDATION
     *                            SKIP_VALIDATION}: Bypass validation of
     *                            connection to this data sink.
     *                            Supported values:
     *                            <ul>
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#TRUE
     *                            TRUE}
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FALSE
     *                            FALSE}
     *                            </ul>
     *                            The default value is {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#FALSE
     *                            FALSE}.
     *                                    <li> {@link
     *                            com.gpudb.protocol.AlterDatasinkRequest.DatasinkUpdatesMap#SCHEMA_NAME
     *                            SCHEMA_NAME}: Updates the schema name.  If
     *                            {@code schema_name}
     *                            doesn't exist, an error will be thrown. If
     *                            {@code schema_name} is empty, then the user's
     *                            default schema will be used.
     *                            </ul>
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public AlterDatasinkRequest setDatasinkUpdatesMap(Map<String, String> datasinkUpdatesMap) {
        this.datasinkUpdatesMap = (datasinkUpdatesMap == null) ? new LinkedHashMap<String, String>() : datasinkUpdatesMap;
        return this;
    }

    /**
     * 
     * @return Optional parameters.
     * 
     */
    public Map<String, String> getOptions() {
        return options;
    }

    /**
     * 
     * @param options  Optional parameters.
     * 
     * @return {@code this} to mimic the builder pattern.
     * 
     */
    public AlterDatasinkRequest setOptions(Map<String, String> options) {
        this.options = (options == null) ? new LinkedHashMap<String, String>() : options;
        return this;
    }

    /**
     * This method supports the Avro framework and is not intended to be called
     * directly by the user.
     * 
     * @return the schema object describing this class.
     * 
     */
    @Override
    public Schema getSchema() {
        return schema$;
    }

    /**
     * This method supports the Avro framework and is not intended to be called
     * directly by the user.
     * 
     * @param index  the position of the field to get
     * 
     * @return value of the field with the given index.
     * 
     * @throws IndexOutOfBoundsException
     * 
     */
    @Override
    public Object get(int index) {
        switch (index) {
            case 0:
                return this.name;

            case 1:
                return this.datasinkUpdatesMap;

            case 2:
                return this.options;

            default:
                throw new IndexOutOfBoundsException("Invalid index specified.");
        }
    }

    /**
     * This method supports the Avro framework and is not intended to be called
     * directly by the user.
     * 
     * @param index  the position of the field to set
     * @param value  the value to set
     * 
     * @throws IndexOutOfBoundsException
     * 
     */
    @Override
    @SuppressWarnings("unchecked")
    public void put(int index, Object value) {
        switch (index) {
            case 0:
                this.name = (String)value;
                break;

            case 1:
                this.datasinkUpdatesMap = (Map<String, String>)value;
                break;

            case 2:
                this.options = (Map<String, String>)value;
                break;

            default:
                throw new IndexOutOfBoundsException("Invalid index specified.");
        }
    }

    @Override
    public boolean equals(Object obj) {
        if( obj == this ) {
            return true;
        }

        if( (obj == null) || (obj.getClass() != this.getClass()) ) {
            return false;
        }

        AlterDatasinkRequest that = (AlterDatasinkRequest)obj;

        return ( this.name.equals( that.name )
                 && this.datasinkUpdatesMap.equals( that.datasinkUpdatesMap )
                 && this.options.equals( that.options ) );
    }

    @Override
    public String toString() {
        GenericData gd = GenericData.get();
        StringBuilder builder = new StringBuilder();
        builder.append( "{" );
        builder.append( gd.toString( "name" ) );
        builder.append( ": " );
        builder.append( gd.toString( this.name ) );
        builder.append( ", " );
        builder.append( gd.toString( "datasinkUpdatesMap" ) );
        builder.append( ": " );
        builder.append( gd.toString( this.datasinkUpdatesMap ) );
        builder.append( ", " );
        builder.append( gd.toString( "options" ) );
        builder.append( ": " );
        builder.append( gd.toString( this.options ) );
        builder.append( "}" );

        return builder.toString();
    }

    @Override
    public int hashCode() {
        int hashCode = 1;
        hashCode = (31 * hashCode) + this.name.hashCode();
        hashCode = (31 * hashCode) + this.datasinkUpdatesMap.hashCode();
        hashCode = (31 * hashCode) + this.options.hashCode();
        return hashCode;
    }

}
